### ISSUE TITLE
Getting "Cannot change source buffer after pumping has been started" all of a sudden

### ISSUE THREAD

**Issue by JCarran0** [agmen-hu/node-datapumps#33]
Chron jobs that I've been running regularly with datapumps seem to be failing all of a sudden.  I don't believe I've changed any related code.

Any ideas or tips on troubleshooting?

"datapumps": "~0.4.4"
npm -v 3.8.6

Also, I'm using the MongoDB mixin

Here's the full error logged to console:
```
Error in pump (root): MongoError: pool destroyed
/app/node_modules/datapumps/lib/Pump.js:57
        throw new Error('Cannot change source buffer after pumping has been started');
                                               ^

Error: Cannot write sealed buffer
    at Buffer.write (/app/node_modules/datapumps/lib/Buffer.js:46:15)
    at null.<anonymous> (/app/node_modules/datapumps/lib/Pump.js:69:32)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:751:26)
    at resume_ (_stream_readable.js:731:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by novaki** [comment]
This means that the `.from` method was called after `.start()` or `.run()`. Maybe there is a race condition which resulted in this bug, but I need more info to help you. Please send me a backtrace and source code.

**Comment by JCarran0** [comment]
Here's my task code:

```
"use strict";

require('dotenv').load({silent: true});
var datapumps = require('datapumps');
var Pump = datapumps.Pump;
var MongodbMixin = datapumps.mixin.MongodbMixin;
var Promise = require('bluebird');
var mongo = Promise.promisifyAll(require('mongodb'));
var StudentValidateAndLoad = require('../lib/dataTeamEtl/dataTeamStudentValidateAndLoad');
var getMongoClientOptions = require('../lib/mongodb/getMongoClientOptions');
var TaskResult = require('../models/taskResult.js');
var BaseModel = require('hapi-mongo-models').BaseModel;

var parsedArgs = require('minimist')(process.argv.slice(2));

// Defaults
var pullDbUrl = parsedArgs['pull-db'] || process.env.MONGOHQ_URL;
var pullCollection = parsedArgs['pull-col'] || 'etl_students';
var verbose = parsedArgs.verbose || false;
var NPM_TASK_NAME = 'dt-to-stud-col-etl';
var studentQuery = {};
var dbns = 'All DBNs';
var workerId = 0;
var workerCount = 1;

if(parsedArgs.dbns){
  dbns = parsedArgs.dbns.split(',');
  studentQuery = {
    schoolId: {$in: dbns}
  };
}

if (parsedArgs['worker-count']){
  workerCount = parseInt(parsedArgs['worker-count']) || 1;
  if(workerCount > 10) {
    throw new Error('!!! Err: supports at most 10 workers');
  }
}

if(parsedArgs['worker-id']) {
  workerId = parseInt(parsedArgs['worker-id']);
  if (workerId > workerCount){
    throw new Error("!!! Err: worker id cannot be greater than worker count");
  }

  if(workerId <= 0) {
    throw new Error('!!! Err: worker id must greater than zero');
  }
}

// This checks for a need for SSL
var pullMongoOptions = getMongoClientOptions(pullDbUrl);

// Need to make the DB connection ourselves, since datapumps does not support passing options to the MongodbMixin
var whenDbConnected = mongo.connectAsync(pullMongoOptions.dbUrl, pullMongoOptions.options);

var taskResult = new TaskResult({
  name: NPM_TASK_NAME,
  verbose: verbose
});

taskResult.results.status = {
  workerCount: workerCount,
  workerId: workerId,
  dbns: dbns,
  countInserted: 0,
  countUpdated: 0,
  countProcessed: 0,
  errors: {
    validation: 0
  }
};



var studentValidateAndLoad = new StudentValidateAndLoad({
  verbose: verbose,
  taskResult: taskResult
});


whenDbConnected.then(
  function(dbConn){
    taskResult.startTask();
    pumpAway(dbConn);
  })
  .catch(err => {
    taskResult.logError(err);
  });



function pumpAway(db) {
  taskResult.logVerbose('Started at ' + taskResult.startedAt);
  taskResult.logVerbose('For DBNs ' + dbns);
  taskResult.logVerbose('Worker ID: ' + workerId);
  taskResult.logVerbose('Worker count: ' + workerCount);

  BaseModel.db = db;

  var extractPump = new Pump();
  extractPump
    .mixin(MongodbMixin(db))
    .useCollection(pullCollection)
    .from(extractPump.find(studentQuery))
    .process(function(etlStudent){
      var studentId = etlStudent.studentId;
      var lastDigit = parseInt(studentId.slice(-1));
      var runThisJob = false;

      if (lastDigit % workerCount === workerId){
        runThisJob = true;
      }

      if(runThisJob) {
        taskResult.logVerbose('  Processing student ' + etlStudent._id);
        return studentValidateAndLoad.processStudentAsync(etlStudent)
          .catch(function(err){
            taskResult.logError(err, `[_id: ${etlStudent._id} ]`);
          });
      } else {
        taskResult.logVerbose('  Skipping student ' + etlStudent._id);
        return Promise.resolve();
      }
    })
    .logErrorsToConsole()
    .run()
    .then(function(){
      outputStatus();
    });
}


function outputStatus() {
  taskResult.endTask();
  taskResult.printStatus();
  taskResult.log(' - students processed: ' + studentValidateAndLoad.status().countProcessed);
  taskResult.log(' - existing students updated: ' + studentValidateAndLoad.status().countUpdated);
  taskResult.log(' - new students inserted: ' + studentValidateAndLoad.status().countInserted);

  taskResult.validateAndInsert(err => {
    if(err) {
      console.log('Could not save task result. Here\'s the JSON:');
      console.error(err);
      console.log('\n');
      console.log(JSON.stringify(taskResult));
    }
    process.exit(0);
  });
}
```

**Comment by novaki** [comment]
I'd start to investigate the first line of log: "MongoError: pool destroyed". This comes from mongodb driver and this is probably the root cause. Also, enable debug mode by calling `.debug()` on pump before calling `.run()`. This will print stack trace with the first error.

**Comment by JCarran0** [comment]
OK, I'm logging bugs now.  Does this tell you anything?  Trying to make sense of this output:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-08-09T15:39:23.760Z [(root)] Pump started
2016-08-09T15:39:24.826Z [(root)] input: 178 items, 179 in, 1 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:26.003Z [(root)] input: 356 items, 180 in, 2 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:27.134Z [(root)] input: 459 items, 104 in, 1 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:28.139Z [(root)] input: 645 items, 189 in, 3 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:29.232Z [(root)] input: 830 items, 186 in, 1 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:30.466Z [(root)] input: 1000 items, 172 in, 2 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:31.483Z [(root)] input: 1000 items, 5 in, 5 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:32.770Z [(root)] input: 1000 items, 11 in, 11 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:33.802Z [(root)] input: 1000 items, 11 in, 11 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:34.862Z [(root)] input: 1000 items, 11 in, 11 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:35.907Z [(root)] input: 1000 items, 11 in, 11 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:36.929Z [(root)] input: 1000 items, 18 in, 18 out | output: 0 items, 0 in, 0 out |
2016-08-09T15:39:37.994Z [(root)] input: 1000 items, 13 in, 13 out | output: 0 items, 0 in, 0 out |
Error in pump (root):
MongoError: pool destroyed
    at Pool.write (/app/node_modules/mongodb-core/lib/connection/pool.js:825:15)
    at WireProtocol.getMore (/app/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:141:14)
    at Cursor._getmore (/app/node_modules/mongodb-core/lib/cursor.js:282:35)
    at nextFunction (/app/node_modules/mongodb-core/lib/cursor.js:603:12)
    at Cursor.next [as _next] (/app/node_modules/mongodb-core/lib/cursor.js:681:3)
    at nextObject (/app/node_modules/mongodb/lib/cursor.js:673:8)
    at Cursor.next (/app/node_modules/mongodb/lib/cursor.js:262:12)
    at Cursor._read (/app/node_modules/mongodb/lib/cursor.js:1067:8)
    at Readable.read (_stream_readable.js:329:10)
    at flow (_stream_readable.js:744:26)
    at resume_ (_stream_readable.js:724:3)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
/app/node_modules/datapumps/lib/Pump.js:57
        throw new Error('Cannot change source buffer after pumping has been started');
                                               ^

Error: Cannot write sealed buffer
    at Buffer.write (/app/node_modules/datapumps/lib/Buffer.js:46:15)
    at null.<anonymous> (/app/node_modules/datapumps/lib/Pump.js:69:32)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at Readable.read (_stream_readable.js:361:10)
    at flow (_stream_readable.js:744:26)
    at resume_ (_stream_readable.js:724:3)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

**Comment by JCarran0** [comment]
The problem seems to be with the mongo node driver package mongodb v ~2.2.5.  When I revert back to ~2.0.40 the error goes away.  

Thanks for the help and the great etl tool!

**Comment by novaki** [comment]
Maybe solving #31 would solve this issue too. Until that, 2.0 mongodb driver is required.
